/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export function OrgCreateDialog({
  open,
  onOpenChange,
  onCreated,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  onCreated?: (org: { id: string; name: string; slug: string }) => void;
}) {
  const router = useRouter();
  const [name, setName] = React.useState("");
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  const submit = async (e?: React.FormEvent) => {
    e?.preventDefault();
    setError(null);
    if (!name) return setError("Organization name is required");
    setLoading(true);
    try {
      const res = await fetch("http://localhost:3001/organizations", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name: name.trim() }),
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to create");
      const org = await res.json();
      onCreated?.(org);
      onOpenChange(false);
      // show success and navigate to new org projects
      toast.success("Organization created");
      if (org?.slug) router.push(`/org/${org.slug}/projects`);
    } catch (err: any) {
      setError(err?.message || "Create failed");
      toast.error(err?.message || "Create failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create Organization</DialogTitle>
          <p className="mt-1 text-sm text-gray-600">
            Create an organization to manage projects, feature flags and invite
            collaborators.
          </p>
        </DialogHeader>

        <form onSubmit={submit} className="grid gap-4">
          <div>
            <label className="text-sm font-medium">Name</label>
            <Input
              placeholder="Acme Company"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </div>
          {/* slug is generated by the server; no input needed */}
          {error && <div className="text-sm text-red-500">{error}</div>}

          <DialogFooter>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={() => onOpenChange(false)}
                disabled={loading}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={loading}>
                {loading ? "Creating…" : "Create"}
              </Button>
            </div>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
